// Generated by Wrangler on Fri Apr 05 2024 15:57:05 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AMPLIFY_BUCKET: R2Bucket;
	AMPLIFY_DB: D1Database;
}
